apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  POSTGRES_SVC: {{quote .Values.postgresql.fullnameOverride}}
  POSTGRES_PORT: {{quote .Values.postgresql.databasePort}}
  POSTGRES_DB: {{quote .Values.postgresql.postgresqlDatabase}}
  POSTGRES_USER: {{quote .Values.postgresql.postgresqlUsername}}
  POSTGRES_PASSWORD: {{quote .Values.postgresql.postgresqlPassword}}
